"""
Train Clifton Strengths fusion model from data.
"""
import json
import pickle
import os
import sys
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

from fusion_model import CliftonFusionModel


def load_data(json_path: str):
    """Load training data generated by LLM."""
    with open(json_path, 'r') as f:
        data = json.load(f)
    return data


def prepare_training_data(data_list):
    """Convert data to feature matrix and labels."""
    model = CliftonFusionModel(model_dir='')  # For feature extraction

    X = []
    y = []

    for sample in data_list:
        # Simulate Whisper output
        whisper_result = {
            'transcript': sample['transcript'],
            'confidence': sample.get('transcript_confidence', 0.9)
        }

        # Simulate VocalTone output
        vocaltone_result = {
            'pitch_mean': sample['pitch_mean'],
            'pitch_std': sample.get('pitch_std', 20.0),
            'tempo': sample['tempo'],
            'energy_level': sample['energy_level'],
            'emotion': sample['emotion'],
            'confidence': sample.get('emotion_confidence', 0.85)
        }

        # Extract features
        features = model.extract_features(whisper_result, vocaltone_result)
        X.append(features.flatten())
        y.append(sample['domain'])

    return np.array(X), np.array(y)


def train_model(X, y, output_dir='models'):
    """Train Random Forest classifier."""
    os.makedirs(output_dir, exist_ok=True)

    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    print(f'Training set: {len(X_train)} samples')
    print(f'Test set: {len(X_test)} samples')

    # Encode labels
    label_encoder = LabelEncoder()
    y_train_encoded = label_encoder.fit_transform(y_train)
    y_test_encoded = label_encoder.transform(y_test)

    print(f'\nDomain classes: {label_encoder.classes_}')

    # Scale features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Train Random Forest
    print('\nTraining Random Forest...')
    clf = RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        min_samples_split=5,
        random_state=42,
        class_weight='balanced'
    )
    clf.fit(X_train_scaled, y_train_encoded)

    # Cross-validation
    print('\nCross-validation scores:')
    cv_scores = cross_val_score(clf, X_train_scaled, y_train_encoded, cv=5)
    print(f'CV Accuracy: {cv_scores.mean():.3f} (+/- {cv_scores.std() * 2:.3f})')

    # Evaluate on test set
    y_pred = clf.predict(X_test_scaled)
    test_accuracy = (y_pred == y_test_encoded).mean()
    print(f'\nTest Accuracy: {test_accuracy:.3f}')

    print('\nClassification Report:')
    print(classification_report(y_test_encoded, y_pred, target_names=label_encoder.classes_))

    print('\nConfusion Matrix:')
    cm = confusion_matrix(y_test_encoded, y_pred)
    print(cm)

    # Feature importance
    print('\nTop 10 Feature Importances:')
    feature_names = ['word_count', 'speech_rate', 'transcript_conf',
                     'exec_keywords', 'infl_keywords', 'rel_keywords', 'strat_keywords',
                     'pitch_mean', 'pitch_std', 'tempo', 'energy', 'emotion_score', 'emotion_conf']
    importances = sorted(zip(feature_names, clf.feature_importances_), key=lambda x: x[1], reverse=True)
    for name, importance in importances[:10]:
        print(f'  {name}: {importance:.4f}')

    # Save model
    with open(os.path.join(output_dir, 'clifton_fusion_model.pkl'), 'wb') as f:
        pickle.dump(clf, f)
    with open(os.path.join(output_dir, 'clifton_scaler.pkl'), 'wb') as f:
        pickle.dump(scaler, f)
    with open(os.path.join(output_dir, 'clifton_labels.pkl'), 'wb') as f:
        pickle.dump(label_encoder, f)

    print(f'\n✓ Model saved to {output_dir}/')
    print(f'  - clifton_fusion_model.pkl')
    print(f'  - clifton_scaler.pkl')
    print(f'  - clifton_labels.pkl')

    return clf, scaler, label_encoder


if __name__ == '__main__':
    # Load data
    data_path = 'training_data/data.json'
    print(f'Loading data from {data_path}...')

    if not os.path.exists(data_path):
        print(f'ERROR: Training data not found at {data_path}')
        print('Please generate training data first using an LLM.')
        sys.exit(1)

    data = load_data(data_path)
    print(f'Loaded {len(data)} samples')

    # Check domain distribution
    from collections import Counter
    domain_counts = Counter(d['domain'] for d in data)
    print(f'\nDomain distribution:')
    for domain, count in sorted(domain_counts.items()):
        print(f'  {domain}: {count}')

    # Prepare training data
    print('\nExtracting features...')
    X, y = prepare_training_data(data)
    print(f'Feature matrix shape: {X.shape}')
    print(f'Features per sample: {X.shape[1]}')

    # Train
    print('\n' + '='*60)
    print('TRAINING MODEL')
    print('='*60)
    train_model(X, y)

    print('\n✓ Training complete!')